language: android

branches:
  only:
    - master

jdk:
  - oraclejdk8

android:
  components:
    - tools-26.1.1
    - build-tools-28.0.3
    - android-28
    - extra-android-support
licenses:
    - 'android-sdk-license-.+'

before_install:
  - yes | sdkmanager "platforms;android-28"
  - chmod +x gradlew

after_success:
  - ./gradlew spaceKiller:jacocoTestReport spaceKiller:coveralls

script:
  ./gradlew clean bundleUnsignedRelease check

# Cache gradle dependencies (should be faster to download them from cache)
cache:
  directories:
  - $HOME/.gradle/wrapper
  - $HOME/.gradle/caches
  - $HOME/.gradle/caches/modules-2/files-2.1
  - $HOME/.android/build-cache
